package Main;

import Excepciones.FueraDeRango;
import Excepciones.ListaVacia;
import Excepciones.NombreNulo;
import java.io.IOException;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private Encriptar encriptar;

    public Interfaz() {
        initComponents();
        encriptar = new Encriptar();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAEntrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTASalida = new javax.swing.JTextArea();
        jBEncriptar = new javax.swing.JButton();
        jBDesencriptar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Segundo Bimestre");

        jTAEntrada.setColumns(20);
        jTAEntrada.setRows(5);
        jScrollPane1.setViewportView(jTAEntrada);

        jTASalida.setColumns(20);
        jTASalida.setRows(5);
        jScrollPane2.setViewportView(jTASalida);

        jBEncriptar.setText("Encriptar");
        jBEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEncriptarActionPerformed(evt);
            }
        });

        jBDesencriptar.setText("Desencriptar");
        jBDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesencriptarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBDesencriptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEncriptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jBEncriptar)
                        .addGap(35, 35, 35)
                        .addComponent(jBDesencriptar)
                        .addGap(41, 41, 41)
                        .addComponent(jBLimpiar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEncriptarActionPerformed
        try {
            //obtenemos el texto ingresado en la caja de texto
            String texto = jTAEntrada.getText();
            //Verificamos que la cadena no sea nula, si lo es se lanza una excepcion
            if (texto.length() == 0) {
                JOptionPane.showMessageDialog(null, "Error. No hay datos que comprimir", "Error", JOptionPane.ERROR_MESSAGE);
                throw new NombreNulo();
            }
            //Utilizamos la funcion comprimir del objeto winzip y le pasamos la cadena a comprimir
            String[] cadenas = encriptar.Encriptacion(texto);
            //Mostramos la cadena de direcciones y la cadena de bytes
            jTASalida.setText("Direcciones: " + cadenas[0]);
        } catch (FueraDeRango e1) {
            e1.printStackTrace();
        } catch (ListaVacia e1) {
            e1.printStackTrace();
        } catch (IOException e1) {
            e1.printStackTrace();
        } catch (NombreNulo e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_jBEncriptarActionPerformed

    private void jBDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesencriptarActionPerformed

        try {

            jTAEntrada.setText("");
            //Utilizamos la funcion descomprimir de la clase Encriptar
            jTASalida.setText("El mensaje original es: " + encriptar.Descomprimir());

        } catch (IOException e1) {
            e1.printStackTrace();
        } catch (NombreNulo e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

    }//GEN-LAST:event_jBDesencriptarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed

        //Limpiamos las cajas de texto
        jTASalida.setText("");
        jTAEntrada.setText("");


    }//GEN-LAST:event_jBLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDesencriptar;
    private javax.swing.JButton jBEncriptar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAEntrada;
    private javax.swing.JTextArea jTASalida;
    // End of variables declaration//GEN-END:variables
}
